import fs from 'node:fs';
import process from 'node:process';

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const manifest = readJson('manifest.json');
const pkg = readJson('package.json');
const versions = readJson('versions.json');
const errors = [];

if (manifest.version !== '1.8.0') errors.push(`manifest.json version must be 1.8.0 (got ${manifest.version}).`);
if (pkg.version !== manifest.version) errors.push(`package.json (${pkg.version}) and manifest.json (${manifest.version}) versions differ.`);
if (!versions[manifest.version]) errors.push(`versions.json is missing ${manifest.version}.`);
if (versions[manifest.version] !== manifest.minAppVersion) errors.push(`versions.json ${manifest.version} floor does not match manifest.minAppVersion.`);
if (!/^[a-z0-9-]+$/.test(manifest.id) || manifest.id.includes('obsidian')) errors.push(`Invalid plugin id: ${manifest.id}.`);
if (!manifest.name || !manifest.description || !manifest.author) errors.push('Manifest is missing required descriptive fields.');
if (!fs.existsSync('README.md')) errors.push('README.md is missing.');
if (!fs.existsSync('LICENSE')) errors.push('LICENSE is missing.');
if (!fs.existsSync('styles.css')) errors.push('styles.css is missing.');
if (!fs.existsSync('main.js')) errors.push('main.js is missing; run npm run build first.');
if (fs.existsSync('main.js')) {
  const main = fs.readFileSync('main.js', 'utf8');
  if (!main.includes('THIS IS A GENERATED/BUNDLED FILE BY ESBUILD')) errors.push('main.js does not appear to be the production esbuild artifact.');
  if (main.includes('sourceMappingURL=data:')) errors.push('Production main.js unexpectedly contains an inline source map.');
}

if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}
console.log(`Release metadata/assets verified for LaTeX Toolbox ${manifest.version}.`);
